### ISSUE TITLE
No module named plaid.utils._normalization error

### ISSUE THREAD

**Issue by lisu9706** [amyxlu/plaid#1]
Dear Amy,
I really like your work and I'm very excited to start using this framework in downstream research. However, I am currently encountering a problem. When I try to load the cheap model **CHEAP_pfam_shorten_2_dim_32** with the ID **"j1v1wv6w",** it reports the following error: **"No module named plaid.utils._normalization"**. Could you update the cheap's Huggingface codebase so that the weights of **CHEAP_pfam_shorten_2_dim_32** are not dependent on the **plaid** ?
All the best,
Lily

**Comment by amyxlu** [comment]
Hi Lily, thanks for your interest in the model and apologies for the delay. I've just updated the checkpoint for https://huggingface.co/amyxlu/cheap-proteins/tree/main/checkpoints/j1v1wv6w. Closing this issue for now, but please do re-open it if you're still having issues.
